/* 文案摘自《老板SBTI图鉴》最新版 + 《老板SBTI测评小问卷_新版答题逻辑与结果》；
 * 新版结果池共 28 种人格；已删除旧稿残留的 NULL / CLOWN / GHOST / TOXIC 以及 FAKE（更名为 BUSY）。
 */
window.BOSS_TYPES = {
  SUCKER: {
    code: "SUCKER",
    name: "趴你身上嘬出火星子的吸血虫",
    desc: "他最大的管理哲学是：员工不是人，是可再生资源。你越能干，他越觉得自己省钱；你越痛苦，他越觉得你成长了。",
    behavior: "榨产出、压成本、不给回报，还要你感谢平台。",
    horror: "★★★★★",
    keywordDanger: "年轻人要多锻炼。",
    image: "assets/bosses/SUCKER.jpg",
  },
  NIGHTer: {
    code: "NIGHT-er",
    name: "白天装死晚上诈尸的夜间索命者",
    desc: "白天像植物人，晚上像厉鬼复活。你刚洗完澡，他发需求；你刚躺下，他说「简单改一下」。",
    behavior: "晚上十一点突然高强度上线。",
    horror: "★★★★☆",
    keywordDanger: "睡了吗？有个小事。",
    image: "assets/bosses/NIGHTer.jpg",
  },
  PUAer: {
    code: "PUA-er",
    name: "一张嘴能把驴骗成阿胶的洗脑仙人",
    desc: "他不一定会提升你的能力，但一定会降低你的自尊。他擅长把压榨包装成培养，把羞辱包装成鞭策。",
    behavior: "长期精神打压，让你怀疑自己不配休息、不配涨薪、不配做人。",
    horror: "★★★★★",
    keywordDanger: "吃亏是福，你要懂得感恩。",
    image: "assets/bosses/PUAer.jpg",
  },
  CAKE: {
    code: "CAKE",
    name: "意大利千层饼主厨",
    desc: "未来讲得很香，现实饿得发慌。他的饼又大又圆，就是不能吃。",
    behavior: "用愿景代替工资，用梦想抵扣奖金。",
    horror: "★★★★☆",
    keywordDanger: "公司将来不会亏待你的。",
    image: "assets/bosses/CAKE.jpg",
  },
  OTOT: {
    code: "OTOT",
    name: "恨不得活人祭祀然后拿你骨灰当燃料的缺德玩意儿",
    desc: "他默认你的生命就是公司备用电池。白天上班，晚上续命，周末充公，节假日献祭。",
    behavior: "加班强度拉满，还假装这是团队奋斗氛围。",
    horror: "★★★★★",
    keywordDanger: "今天辛苦一下。",
    image: "assets/bosses/OTOT.jpg",
  },
  TRASH: {
    code: "TRASH",
    name: "脑袋里的水能养鱼的草包废物",
    desc: "能力低，声音大，脑袋空，架子大。他不解决问题，但非常擅长制造问题后骂别人。",
    behavior: "不懂业务，但爱指挥；不出方案，但爱否定。",
    horror: "★★★★☆",
    keywordDanger: "你们自己解决，别问我。",
    image: "assets/bosses/TRASH.jpg",
  },
  BRICK: {
    code: "BRICK",
    name: "半句建议都灌不进去的倔驴",
    desc: "固执、僵硬、听不进话。你给他讲逻辑，他给你讲经验；你给他看数据，他说「我感觉不是这样」。",
    behavior: "错误路线坚持到底，撞南墙也要怪墙。",
    horror: "★★★★☆",
    keywordDanger: "我以前都是这么做的。",
    image: "assets/bosses/BRICK.jpg",
  },
  THIEF: {
    code: "THIEF",
    name: "你做饭端锅TA悠闲上桌的职场偷子",
    desc: "你熬夜做方案，他白天拿去领奖。你负责燃烧，他负责发光。",
    behavior: "成果全归他，问题全归你。",
    horror: "★★★★★",
    keywordDanger: "这个项目是我一手带出来的。",
    image: "assets/bosses/THIEF.jpg",
  },
  SAINT: {
    code: "SAINT",
    name: "情怀满汉全席工资腹痛拉稀的神棍",
    desc: "天天讲奉献、格局、使命、情怀，但一谈工资就瞬间涅槃圆寂。",
    behavior: "让你牺牲生活，成全他的利润。",
    horror: "★★★★☆",
    keywordDanger: "除了工资，你就没有在意的东西了吗？",
    image: "assets/bosses/SAINT.jpg",
  },
  CULT: {
    code: "CULT",
    name: "拿企业文化做法的邪教教主",
    desc: "他不是在管理公司，他是在创办宗教。公司文化像教义，老板讲话像神谕，员工离职像叛教。",
    behavior: "要求绝对忠诚，把质疑当异端。",
    horror: "★★★★★",
    keywordDanger: "要把公司当家。",
    image: "assets/bosses/CULT.jpg",
  },
  CCTV: {
    code: "CCTV",
    name: "对你拉屎时长了如指掌的私生饭",
    desc: "他对你的工作成果兴趣一般，但对你在线状态、回复速度、厕所时长极其敏感。",
    behavior: "永远盯着你亮不亮、绿不绿、秒不秒回。",
    horror: "★★★★☆",
    keywordDanger: "怎么上厕所要这么久？",
    image: "assets/bosses/CCTV.jpg",
  },
  AUV: {
    code: "AUV",
    name: "嘴像粪坑开闸说话能把你膈应死的阴阳法师",
    desc: "他说话不直接骂你，但每一句都能让你恶心半天。表面轻飘飘，实则刀片片。",
    behavior: "阴阳怪气、反向夸奖、茶味输出。",
    horror: "★★★☆☆",
    keywordDanger: "你真是个人才。",
    image: "assets/bosses/AUV.jpg",
  },
  MASK: {
    code: "MASK",
    name: "背地里算计你的嘴甜心黑老狐狸",
    desc: "他永远笑眯眯，但刀子也是真的。你以为他在关心你，其实他在给你埋雷。",
    behavior: "表面温和，背后切割；语气很软，手段很狠。",
    horror: "★★★★☆",
    keywordDanger: "我这是为了你好。",
    image: "assets/bosses/MASK.jpg",
  },
  BOOM: {
    code: "BOOM",
    name: "情绪保险丝比见识还短的易燃易爆品",
    desc: "情绪稳定性约等于煤气罐。你不知道哪句话会点燃他，但你知道迟早会炸。",
    behavior: "一点就炸，办公室随机爆破。",
    horror: "★★★★★",
    keywordDanger: "你能干就干，不能干就滚！",
    image: "assets/bosses/BOOM.jpg",
  },
  DADDY: {
    code: "DADDY",
    name: "自己半桶泔水瞎晃还教你做人的爹癌晚期患者",
    desc: "他不是你的老板，他是你上班路上捡到的野生爹。任何话题都能转化成人生教育。",
    behavior: "说教、爹味、端着，一副「我吃过的盐比你吃过的饭多」的样子。",
    horror: "★★★☆☆",
    keywordDanger: "想当年，我刚毕业的时候……",
    image: "assets/bosses/DADDY.jpg",
  },
  TEDX: {
    code: "TEDX",
    name: "唾沫星子能喷你一脸的演讲家",
    desc: "三句话能讲完的事，他能讲成企业家峰会。他不是开会，他是在举办个人巡演。",
    behavior: "长篇输出、喷口水、绕圈子，最后没有结论。",
    horror: "★★★☆☆",
    keywordDanger: "我来简单说两句。",
    image: "assets/bosses/TEDX.jpg",
  },
  KING: {
    code: "KING",
    name: "整天摆谱下圣旨的亡司暴君",
    desc: "天天上班像上朝，公司不大，龙椅很稳。业务一般，圣旨不少。",
    behavior: "唯我独尊，员工进办公室像觐见。",
    horror: "★★★★☆",
    keywordDanger: "你是老板我是老板？",
    image: "assets/bosses/KING.jpg",
  },
  MOON: {
    code: "MOON",
    name: "屎上雕花的白日梦想家",
    desc: "目标永远脱离现实。预算三块五，目标冲火星；团队三个人，计划统治行业。",
    behavior: "定不可能完成的 KPI，然后说你缺乏想象力。",
    horror: "★★★★☆",
    keywordDanger: "我们要做行业第一。",
    image: "assets/bosses/MOON.jpg",
  },
  FOG: {
    code: "FOG",
    name: "成天打哑谜疑似已升天来给你托梦的出题人",
    desc: "他说需求像算命，给反馈像打哑谜。你问具体哪里不好，他说「感觉不对」。",
    behavior: "需求模糊、反复改稿、永远没有明确标准。",
    horror: "★★★★☆",
    keywordDanger: "你自己看这对吗？",
    image: "assets/bosses/FOG.jpg",
  },
  BUSY: {
    code: "BUSY",
    name: "随地大小忙不吃饭不拉屎的「国家领导人」",
    desc: "日程很满，产出为零；会议很多，结论没有。发消息永远不回，一问永远在忙。",
    behavior: "天天开会、天天转发、天天「同步一下」。",
    horror: "★★★☆☆",
    keywordDanger: "我很忙。",
    image: "assets/bosses/BUSY.jpg",
  },
  ROACH: {
    code: "ROACH",
    name: "好死不如赖活着的恶臭小强",
    desc: "项目死了，他没死；部门炸了，他升职。你以为他要完了，结果他又爬出来了。",
    behavior: "极强生存能力，极弱负责能力。",
    horror: "★★★★★",
    keywordDanger: "你们怎么搞的？",
    image: "assets/bosses/ROACH.jpg",
  },
  MONK: {
    code: "MONK",
    name: "血液里流淌着冰美式的苦派禅师",
    desc: "自己不加钱，只劝你修行。没苦硬吃，吃得苦中苦，老板买路虎。",
    behavior: "鼓吹吃苦、牺牲、忍耐，把贫穷包装成美德。",
    horror: "★★★★☆",
    keywordDanger: "年轻人吃点苦是好事。",
    image: "assets/bosses/MONK.jpg",
  },
  SHEET: {
    code: "SHEET",
    name: "疑似母语为 Excel 的表格奴隶主",
    desc: "在他眼里，世界不是由原子组成的，是由 Excel 单元格组成的。任何问题最后都会变成「你先做个表」。",
    behavior: "表格套表格，汇总套汇总，统计套统计。",
    horror: "★★★☆☆",
    keywordDanger: "你拉个表给我。",
    image: "assets/bosses/SHEET.jpg",
  },
  RING: {
    code: "RING",
    name: "电话微信钉钉飞书连环追杀案夺命屠夫",
    desc: "电话、微信、钉钉、邮件，多平台立体轰炸。你不是员工，你是他的人肉通知接收器。",
    behavior: "要求 10 分钟内回复，超过 11 分钟就开始追魂。",
    horror: "★★★★★",
    keywordDanger: "这个应该很快吧？",
    image: "assets/bosses/RING.jpg",
  },
  LEAVE: {
    code: "LEAVE",
    name: "一请假就审你三代怕你越狱的典狱长",
    desc: "在他眼里，员工没有生病、家事、急事，只有「不够敬业」。你不是人，你是全年无休的办公耗材。",
    behavior: "请一天假，审你三代；请半天假，怀疑你跑路。哪怕你发烧到 39 度，他也会问：「那你能不能线上看一下？」",
    horror: "★★★★★",
    keywordDanger: "怎么又请假？",
    image: "assets/bosses/LEAVE.jpg",
  },
  GOLD: {
    code: "GOLD",
    name: "百年难遇的限量版财神爷",
    desc: "少见的神话级存在。画饼不是重点，重点是他真发钱。老板好爽又大气，生意越做越如意。",
    behavior: "奖金真发，承诺兑现，功劳认账。",
    horror: "☆☆☆☆☆",
    luck: "★★★★★",
    keywordHappy: "大家来领红包。",
    image: "assets/bosses/GOLD.jpg",
  },
  COVER: {
    code: "COVER",
    name: "关键时刻永远站第一排扛事儿的救命恩人",
    desc: "真正的成年人。你捅篓子，他帮你收场；你遇到压力，他挡在前面。",
    behavior: "保护团队，承担责任，不让下属当炮灰。",
    horror: "☆☆☆☆☆",
    luck: "★★★★★",
    keywordHappy: "这个我来处理。",
    image: "assets/bosses/COVER.jpg",
  },
  NURSE: {
    code: "NURSE",
    name: "把你当孩子照顾的管理界天使",
    desc: "他不是来榨干你的，他是来确认你还活着的。能发现你今天状态不对，也会认真问一句「要不要先休息一下？」在他手下工作，至少你会觉得自己不是一台插电打工机。",
    behavior: "开会前先看大家脸色，deadline 前先问工作量是否合理。遇到突发状况，不会第一时间追责，而是先把人稳住、把事拆开。",
    horror: "☆☆☆☆☆",
    heal: "★★★★★",
    keywordSafe: "你先调整一下，事情我们一起想办法。",
    image: "assets/bosses/NURSE.jpg",
  },
};

window.TYPE_SCORE_KEYS = Object.keys(window.BOSS_TYPES);
