/* 文案与星级摘自《老板SBTI图鉴.pdf》图鉴部分；内部键与题库计分一致 */
window.BOSS_TYPES = {
  NIGHTer: { code: "NIGHT-er", name: "夜间索命者", desc: "白天像植物人，晚上像厉鬼复活。你刚洗完澡，他发需求；你刚躺下，他说「简单改一下」。", behavior: "晚上十一点突然高强度上线。", horror: "★★★★☆", keywordDanger: "睡了吗？有个小事。" },
  SUCKER: { code: "SUCKER", name: "吸血寄生虫", desc: "他最大的管理哲学是：员工不是人，是可再生资源。你越能干，他越觉得自己省钱；你越痛苦，他越觉得你成长了。", behavior: "榨产出、压成本、不给回报，还要你感谢平台。", horror: "★★★★★", keywordDanger: "年轻人要多锻炼。" },
  PUAer: { code: "PUA-er", name: "洗脑专家", desc: "他不一定会提升你的能力，但一定会降低你的自尊。他擅长把压榨包装成培养，把羞辱包装成鞭策。", behavior: "长期精神打压，让你怀疑自己不配休息、不配涨薪、不配做人。", horror: "★★★★★", keywordDanger: "你这个心态不对。" },
  TRASH: { code: "TRASH", name: "废物老板", desc: "能力低，声音大，脑袋空，架子大。他不解决问题，但非常擅长制造问题后骂别人。", behavior: "不懂业务，但爱指挥；不出方案，但爱否定。", horror: "★★★★☆", keywordDanger: "这还要我教你？" },
  OTOT: { code: "OTOT", name: "烧命鬼", desc: "他默认你的生命就是公司备用电池。白天上班，晚上续命，周末充公，节假日献祭。", behavior: "加班强度拉满，还假装这是团队奋斗氛围。", horror: "★★★★★", keywordDanger: "" },
  THIEF: { code: "THIEF", name: "偷功大师", desc: "你熬夜做方案，他白天拿去领奖。你负责燃烧，他负责发光。", behavior: "成果全归他，问题全归你。", horror: "★★★★★", keywordDanger: "这个项目是我带出来的。" },
  SAINT: { code: "SAINT", name: "圣者", desc: "天天讲奉献、格局、使命、情怀，但一谈工资就瞬间涅槃圆寂。", behavior: "让你牺牲生活，成全他的利润。", horror: "★★★★☆", keywordDanger: "" },
  NULL: { code: "NULL", name: "空壳领导", desc: "职位很高，内容没有。像公司系统里的一个占位符，占资源、占流程、占会议，但不产生任何有效信息。", behavior: "关键时刻只会说「你们再讨论一下」。", horror: "★★★☆☆", keywordDanger: "这个事情你们先推进。" },
  BRICK: { code: "BRICK", name: "砖头脑袋", desc: "固执、僵硬、听不进话。你给他讲逻辑，他给你讲经验；你给他看数据，他说「我感觉不是这样」。", behavior: "错误路线坚持到底，撞南墙也要怪墙。", horror: "★★★★☆", keywordDanger: "以前都是这么做的。" },
  TOXIC: { code: "TOXIC", name: "情绪毒源", desc: "他本人就是办公室核废料。只要他一进门，空气质量指数立刻爆表。", behavior: "用坏情绪污染全员，让大家每天上班像吸毒气。", horror: "★★★★★", keywordDanger: "这点事都做不好？" },
  AUV: { code: "AUV", name: "老阴阳家", desc: "他说话不直接骂你，但每一句都能让你恶心半天。表面轻飘飘，实则刀片片。", behavior: "阴阳怪气、反向夸奖、茶味输出。", horror: "★★★☆☆", keywordDanger: "不要只盯着钱。" },
  CULT: { code: "CULT", name: "邪教上帝", desc: "他不是在管理公司，他是在创办宗教。公司文化像教义，老板讲话像神谕，员工离职像叛教。", behavior: "要求绝对忠诚，把质疑当异端。", horror: "★★★★★", keywordDanger: "要把公司当家。" },
  CCTV: { code: "CCTV", name: "监控摄像头", desc: "他对你的工作成果兴趣一般，但对你在线状态、回复速度、厕所时长极其敏感。", behavior: "永远盯着你亮不亮、绿不绿、秒不秒回。", horror: "★★★★☆", keywordDanger: "你刚才怎么没回？" },
  DADDY: { code: "DADDY", name: "爹癌患者", desc: "他不是你的老板，他是你上班路上捡到的野生爹。任何话题都能转化成人生教育。", behavior: "说教、爹味、端着，一副「我吃过的盐比你吃过的饭多」的样子。", horror: "★★★☆☆", keywordDanger: "年轻人还是不要太浮躁" },
  TEDX: { code: "TEDX", name: "演讲者", desc: "三句话能讲完的事，他能讲成企业家峰会。他不是开会，他是在举办个人巡演。", behavior: "长篇输出、喷口水、绕圈子，最后没有结论。", horror: "★★★☆☆", keywordDanger: "我最后说两句。" },
  MASK: { code: "MASK", name: "温柔刀", desc: "他永远笑眯眯，但刀子也是真的。你以为他在关心你，其实他在给你埋雷。", behavior: "表面温和，背后切割；语气很软，手段很狠。", horror: "★★★★☆", keywordDanger: "我这是为团队好。" },
  BOOM: { code: "BOOM", name: "易燃易爆品", desc: "情绪稳定性约等于煤气罐。你不知道哪句话会点燃他，但你知道迟早会炸。", behavior: "一点就炸，办公室随机爆破。", horror: "★★★★★", keywordDanger: "？" },
  FOG: { code: "FOG", name: "迷雾制造机", desc: "他说需求像算命，给反馈像打哑谜。你问具体哪里不好，他说「感觉不对」。", behavior: "需求模糊、反复改稿、永远没有明确标准。", horror: "★★★★☆", keywordDanger: "不对。" },
  KING: { code: "KING", name: "末代皇帝", desc: "天天上班像上朝，公司不大，龙椅很稳。业务一般，圣旨不少。", behavior: "唯我独尊，员工进办公室像觐见。", horror: "★★★★☆", keywordDanger: "你是老板我是老板？" },
  MOON: { code: "MOON", name: "登月者", desc: "目标永远脱离现实。预算三块五，目标冲火星；团队三个人，计划统治行业。", behavior: "定不可能完成的 KPI，然后说你缺乏想象力。", horror: "★★★★☆", keywordDanger: "我们要做行业第一。" },
  COVER: { code: "COVER", name: "团队靠山", desc: "真正的成年人。你捅篓子，他帮你收场；你遇到压力，他挡在前面。", behavior: "保护团队，承担责任，不让下属当炮灰。", horror: "☆☆☆☆☆", luck: "★★★★★", keywordHappy: "这个我来处理。" },
  FAKE: { code: "FAKE", name: "假忙大师", desc: "日程很满，产出为零；会议很多，结论没有。他不是在工作，他是在表演自己很忙。", behavior: "天天开会、天天转发、天天「同步一下」。", horror: "★★★☆☆", keywordDanger: "我今天排满了。" },
  ROACH: { code: "ROACH", name: "蟑螂型老板", desc: "项目死了，他没死；部门炸了，他升职。你以为他要完了，结果他又爬出来了。", behavior: "极强生存能力，极弱负责能力。", horror: "★★★★★", keywordDanger: "你们尽快反思一下。" },
  GOLD: { code: "GOLD", name: "财神爷", desc: "少见的神话级存在。画饼不是重点，重点是他真发钱。", behavior: "奖金真发，承诺兑现，功劳认账。", horror: "☆☆☆☆☆", luck: "★★★★★", keywordHappy: "大家辛苦了，给大家发个红包。" },
  CAKE: { code: "CAKE", name: "画饼皇帝", desc: "未来讲得很香，现实饿得发慌。他的饼又大又圆，就是不能吃。", behavior: "用愿景代替工资，用梦想抵扣奖金。", horror: "★★★★☆", keywordDanger: "以后空间很大。" },
  RING: { code: "RING", name: "连环催命王", desc: "电话、微信、钉钉、邮件，多平台立体轰炸。你不是员工，你是他的人肉通知接收器。", behavior: "要求 10 分钟内回复，超过 11 分钟就开始追魂。", horror: "★★★★★", keywordDanger: "这个应该很快吧？" },
  MONK: { code: "MONK", name: "苦行僧传销师", desc: "自己不加钱，只劝你修行。没苦硬吃，吃得苦中苦，老板买路虎。", behavior: "鼓吹吃苦、牺牲、忍耐，把贫穷包装成美德。", horror: "★★★★☆", keywordDanger: "年轻人吃点苦是好事。" },
  SHEET: { code: "SHEET", name: "表格奴隶主", desc: "在他眼里，世界不是由原子组成的，是由单元格组成的。任何问题最后都会变成「你先做个表」。", behavior: "表格套表格，汇总套汇总，统计套统计。", horror: "★★★☆☆", keywordDanger: "你拉个表给我。" },
  LEAVE: { code: "LEAVE", name: "假条粉碎机", desc: "在他眼里，员工没有生病、家事、急事，只有「不够敬业」。你不是人，你是全年无休的办公耗材。", behavior: "请一天假，审你三代；请半天假，怀疑你跑路。哪怕你发烧到 39 度，他也会问：「那你能不能线上看一下？」", horror: "★★★★★", keywordDanger: "怎么又请假？" },
  NURSE: { code: "NURSE", name: "工位护士长", desc: "他不是来榨干你的，他是来确认你还活着的。能发现你今天状态不对，也会认真问一句「要不要先休息一下？」在他手下工作，至少你会觉得自己不是一台插电打工机。", behavior: "开会前先看大家脸色，deadline 前先问工作量是否合理。遇到突发状况，不会第一时间追责，而是先把人稳住、把事拆开。", horror: "☆☆☆☆☆", heal: "★★★★★", keywordSafe: "你先调整一下，事情我们一起想办法。" },
  GHOST: { code: "GHOST", name: "背后灵（图鉴计分用）", desc: "与「第一时间消失、别人背完锅后再出来总结」类老板画像强相关。", behavior: "关键时刻隐身，复盘时现身。", horror: "★★★★☆", keywordDanger: "" },
  CLOWN: { code: "CLOWN", name: "小丑型（图鉴计分用）", desc: "人菜瘾大还爱装，典型职场表演型。", behavior: "不懂装懂，爱出风头。", horror: "★★★★☆", keywordDanger: "" },
};

window.TYPE_SCORE_KEYS = Object.keys(window.BOSS_TYPES);
